### ISSUE TITLE
When uploading an image, I'm getting this error "FileNotFoundError at /"

### ISSUE THREAD

**Issue by GentianSadiku** [FarjaalAhmad/django_bgRemoverML#13] opened 2021-03-28 17:55 UTC
When trying to upload an image in localhost (http://127.0.0.1:8000). It's returning an error:

What steps should I follow to make it work? ( I already followed README.md instructions and run setup.sh)

<img width="1792" alt="Screen Shot 2021-03-28 at 19 46 27" src="https://user-images.githubusercontent.com/11274282/112762319-59259600-8fff-11eb-9a67-ebd1a8798c82.png">

**Comment by FarjaalAhmad** [comment] 2021-03-29 11:21
Hey, the error is showing that you didn't run setup.sh. Seems that's the issue, can you please check that out and let me know. Because, if the pre-trained models will not available to the project, it can't be go further.

**Comment by GentianSadiku** [comment] 2021-03-29 18:21
Yep I've checked / run (setup.sh) multiple times. Still getting the same error

**Comment by VenomII01** [comment] 2021-04-23 07:54
I'm getting the same error and literally tried for so long to fix it myself and seems like that there's a problem in (setup.sh) with the directory command lines : 

mv c.pth ../models/basnet/
mv u2net.pth ../models/u2net/
mv u2netp.pth ../models/u2netp/  

I hope it get fixed soon

**Comment by rana-shubham** [comment] 2021-05-10 11:07
I'm getting the same error even all files are there are checked each and everything and acc. to setup.sh

**Comment by FarjaalAhmad** [comment] 2021-05-13 07:54
sorry for reaching out late, 
can you guys please run setup.sh commands manually after creating new dir "setup" with download.py in it? (update: don't execute the last three commented commands.)
cuz, everything is working well for me

**Comment by rana-shubham** [comment] 2021-05-13 08:24
> sorry for reaching out late,
> can you guys please run setup.sh commands manually after creating new dir "setup" with download.py in it? (update: don't execute the last three commented commands.)
> cuz, everything is working well for me

Not working. Tried manually as well. Still the same error

**Comment by Vikasjawla** [comment] 2021-05-13 08:55
I am also getting the same error, tried everything but no success.

**Comment by luizoti** [comment] 2021-05-24 21:45
I wont receive error, but the server stop, in my case i started the server in other port, 9000, i don't know if this is the problem.

**Comment by FarjaalAhmad** [comment] 2021-07-23 07:24
Hey, I updated the setup.sh
You can try the updated file. Maybe that will work for you guys. I don't think there is any issue as everything works fine for me even at the new installation.

**Comment by dataimpactnl** [comment] 2021-07-29 12:50
I stumbled on the same issue but I have resolved it. 
The issue is related to the download of the models. 

When downloading the files with setup.sh I got the following error from Google
`Access denied with the following error:

 	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1s52ek_4YTDRt_EOkx1FS53u-vJa0c4nu`

The steps I took to fix the issue are:

1. Download these files manually in the browser
https://drive.google.com/uc?id=1s52ek_4YTDRt_EOkx1FS53u-vJa0c4nu
https://drive.google.com/uc?id=1rbSTGKAE-MTxBYHd-51l2hMOQPT_7EPy
https://drive.google.com/uc?id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ
2. Create directory "models" inside main directory
3. Create subdirectories "basnet" "u2net" "u2netp" inside the models directory
4. Put the downloaded files inside these directories accordingly
django_bgRemoverML/models/basnet/basnet.pth'
django_bgRemoverML/models/u2net/u2net.pth'
django_bgRemoverML/models/u2netp/u2netp.pth'

**Comment by luizoti** [comment] 2021-07-29 13:34
In this case, perhaps dropbox is an option to save these files.

**Comment by FarjaalAhmad** [comment] 2021-08-12 16:53
> I stumbled on the same issue but I have resolved it.
> The issue is related to the download of the models.
> 
> When downloading the files with setup.sh I got the following error from Google
> `Access denied with the following error:
> 
> ```
> Too many users have viewed or downloaded this file recently. Please
> try accessing the file again later. If the file you are trying to
> access is particularly large or is shared with many people, it may
> take up to 24 hours to be able to view or download the file. If you
> still can't access a file after 24 hours, contact your domain
> administrator. 
> ```
> 
> You may still be able to access the file from the browser:
> 
> ```
>  https://drive.google.com/uc?id=1s52ek_4YTDRt_EOkx1FS53u-vJa0c4nu`
> ```
> 
> The steps I took to fix the issue are:
> 
> 1. Download these files manually in the browser
>    https://drive.google.com/uc?id=1s52ek_4YTDRt_EOkx1FS53u-vJa0c4nu
>    https://drive.google.com/uc?id=1rbSTGKAE-MTxBYHd-51l2hMOQPT_7EPy
>    https://drive.google.com/uc?id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ
> 2. Create directory "models" inside main directory
> 3. Create subdirectories "basnet" "u2net" "u2netp" inside the models directory
> 4. Put the downloaded files inside these directories accordingly
>    django_bgRemoverML/models/basnet/basnet.pth'
>    django_bgRemoverML/models/u2net/u2net.pth'
>    django_bgRemoverML/models/u2netp/u2netp.pth'

Hey, now the setup script is working fine but that's been the restriction from Google. I don't have a File Hosting service for now or else I'll host these files there so that you don't have to face this issue anymore.

BTW, I'm closing this issue because there is nothing left to solve for now.

**Closed as completed by FarjaalAhmad** 2021-08-12 16:53 UTC

**Comment by luizoti** [comment] 2021-08-12 20:47
> > I stumbled on the same issue but I have resolved it.
> > The issue is related to the download of the models.
> > When downloading the files with setup.sh I got the following error from Google
> > `Access denied with the following error:
> > ```
> > Too many users have viewed or downloaded this file recently. Please
> > try accessing the file again later. If the file you are trying to
> > access is particularly large or is shared with many people, it may
> > take up to 24 hours to be able to view or download the file. If you
> > still can't access a file after 24 hours, contact your domain
> > administrator. 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You may still be able to access the file from the browser:
> > ```
> >  https://drive.google.com/uc?id=1s52ek_4YTDRt_EOkx1FS53u-vJa0c4nu`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The steps I took to fix the issue are:
> > 
> > 1. Download these files manually in the browser
> >    https://drive.google.com/uc?id=1s52ek_4YTDRt_EOkx1FS53u-vJa0c4nu
> >    https://drive.google.com/uc?id=1rbSTGKAE-MTxBYHd-51l2hMOQPT_7EPy
> >    https://drive.google.com/uc?id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ
> > 2. Create directory "models" inside main directory
> > 3. Create subdirectories "basnet" "u2net" "u2netp" inside the models directory
> > 4. Put the downloaded files inside these directories accordingly
> >    django_bgRemoverML/models/basnet/basnet.pth'
> >    django_bgRemoverML/models/u2net/u2net.pth'
> >    django_bgRemoverML/models/u2netp/u2netp.pth'
> 
> Hey, now the setup script is working fine but that's been the restriction from Google. I don't have a File Hosting service for now or else I'll host these files there so that you don't have to face this issue anymore.
> 
> BTW, I'm closing this issue because there is nothing left to solve for now.

1. About the google limit, I was testing to rewrite the install script and include the pcloud server, I think it should work, but I ended up not having time to finish.
2. About the problem of sending the file, it still happens, but the strange thing is not returning an error.

I'll test it again when I can, and try to determine what the problem is.
